DROP TABLE IF EXISTS wcf1_person;
CREATE TABLE wcf1_person (
	personID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	firstName VARCHAR(255) NOT NULL,
	lastName VARCHAR(255) NOT NULL,
	comments SMALLINT(5) NOT NULL DEFAULT 0,
	enableComments TINYINT(1) NOT NULL DEFAULT 1
);
