name: Deploy

on:
  push:
    branches:
    - '5.4'
    - '5.5'

jobs:
  deploy:
    concurrency:
      group: target
      cancel-in-progress: true
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip3 install -r requirements.txt
    - name: Prepare git
      run: |
        git config user.name "WoltLab GmbH"
        git config user.email "woltlab@woltlab.com"
    - name: Deploy documentation
      run: mike deploy --branch "target" --push "${GITHUB_REF#refs/heads/}"
